apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: climbr-viz

bases:
  - ../../base

namePrefix: prod-

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 2

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
    target:
      kind: Deployment
      name: backend

  # Keep LoadBalancer for production (cloud environments)
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: frontend-service

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - flask_env=production
      - log_level=WARNING