apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: climbr-viz
  labels:
    app: climbr-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: climbr-backend
  template:
    metadata:
      labels:
        app: climbr-backend
    spec:
      containers:
      - name: backend
        image: your-registry/climbr-backend:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: flask_env
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/pathways
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/pathways
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
          readOnly: true
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: climbr-data-pvc