apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: climbr-viz
  labels:
    app: climbr-backend
spec:
  type: ClusterIP
  selector:
    app: climbr-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http