apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: climbr-viz
  labels:
    app: climbr-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: climbr-backend
  template:
    metadata:
      labels:
        app: climbr-backend
    spec:
      containers:
      - name: backend
        image: climbr-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: flask_env
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 120
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 120
          failureThreshold: 3