apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: climbr-viz
  labels:
    app: climbr-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: climbr-frontend
  template:
    metadata:
      labels:
        app: climbr-frontend
    spec:
      containers:
      - name: frontend
        image: your-registry/climbr-frontend:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5