apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: climbr-data-pvc
  namespace: climbr-viz
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-loader
  namespace: climbr-viz
data:
  init.sh: |
    #!/bin/sh
    if [ ! -f /data/loinc.json ]; then
      cp /app/loinc.json /data/
      cp /app/cpt4.json /data/
    fi